### ISSUE TITLE
rlz plz :)

### ISSUE THREAD

**Issue by RouxRC** [fmassot/cpc-api#1]
@fmassot tu pourrais faire une release pip suite à la rectif https? thx!

**Comment by fmassot** [comment]
done !

**Comment by RouxRC** [comment]
thx
Après en fait mon souci venait surtout de python 2.6 et ssl ;)

**Comment by fmassot** [comment]
cette fameuse compatibilité 2.6, y'en a encore besoin ?

**Comment by RouxRC** [comment]
goya toujours...
Du coup là j'ai craqué et migré la cron en question sur cocolulu
